# Generated by Django 5.2.3 on 2025-06-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
    ]
