# Generated by Django 5.2.3 on 2025-06-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_products_orderitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_amount',
        ),
    ]
